services:
  comfier:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        groupid: 1000
        userid: 1000
    command: --lowvram # Optional, other options are --highvram, --novram, --cpu
    image: ozzah/comfier:latest
    user: 1000:1000
    volumes:
      - /path/to/models/:/ComfyUI/models
      - /path/to/input:/ComfyUI/input
      - /path/to/output:/ComfyUI/output
      - /path/to/workflows:/ComfyUI/pysssss-workflows
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
